name: flutter_base_project
description: This is flutter base project with MVVM architecture.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  path: any

  # Fetch current device information.
  device_info_plus: ^10.1.0

  # Bloc architecture
  flutter_bloc: ^8.1.3

  # Routing navigation
  go_router: ^14.2.0

  # Prevent duplicate object being called.
  equatable: ^2.0.5

  # Get it
  get_it: ^7.6.4

  # Defines the annotations used by json_serializable
  # to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1

  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.7.1

  # About
  about: ^2.1.3

  # avatar glow
  avatar_glow: ^3.0.1

  # networking library
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # check network connection
  connectivity_plus: ^6.1.0

  intl: ^0.19.0

  # flutter webview
  webview_flutter: ^4.4.1

  # infinite scroll pagination
  infinite_scroll_pagination: ^4.0.0

  # shimmer
  shimmer: ^3.0.0

  # cached network image
  cached_network_image: ^3.3.0

  # logger
  logger: ^2.0.2+1

  # badge
  badges: ^3.1.2

  # Test
  bloc_test: ^9.1.4

  get_storage: ^2.1.1

  loader_overlay: ^4.0.3

  #Permission Handler
  permission_handler: ^11.3.0

  #Document picker
  file_picker: ^8.0.0+1

  #Image picker
  image_picker: ^1.1.0

  # shared preferences
  shared_preferences: ^2.2.3

  flutter_dotenv: ^5.2.1

  flutter_svg: ^2.0.10+1

  sqflite: ^2.3.2

  image_cropper: ^8.0.2
  flutter_image_compress: ^2.3.0

  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr: ^2.2.1

  flutter_lints: ^4.0.0

  # The build_runner package provides a
  # concrete way of generating files using Dart code.
  build_runner: ^2.4.6

  test: ^1.24.3

  mocktail: ^1.0.4

  mockito: ^5.4.2

integration_test:
  sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - .env
